= Distributed James Server &mdash; Extending server behavior
:navtitle: Extending server behavior

The Distributed Server exposes several interfaces allowing the user to write custom extensions in
order to extend the Distributed Server behavior.

Writing *Mailets* and *Matchers* allows one to supply custom components for the
xref:distributed/extend/mail-processing.adoc[Mail Processing] and
enables to take decisions, and implement your business logic at the transport level.

Writing xref:distributed/extend/mailbox-listeners.adoc[Mailbox listeners] enables to
react to your user interaction with their mailbox. This powerful tool allows build advanced features
for mail delivery servers.

Writing xref:distributed/extend/smtp-hooks.adoc[SMTP hookd] enables to
add features to your SMTP server.

Writing xref:distributed/extend/webadmin-routes.adoc[WebAdmin routes] enables to
add features to the WebAdmin REST API.

== Handling injections for your extensions

(TODO)

 - Using injections defined by the Distributing Server
 - Adding custom injections to one of the Distributed Server for injections in your extensions.

Note that overriding injection definitions of the Distributed Server for your injections is not supported.
