= Apache James Mail Servers
:navtitle: Servers

James offers five types of ready-made Mail Servers. The servers are intended 
for those with different needs, ranging from Operators
who are interested in setting up a server for the first time, to experienced teams of 
Developers
looking to deploy an advanced distributed system.
Each of the servers has been tested and verified so you can 
deploy a production-grade 
Mail Server with confidence.

The available James Servers are:

 * <<demo,James Demo Mail Server>>
 * <<distributed,James Distributed Mail Server>>
 * <<postgres,James Postgres Mail Server>>
 * <<jpa,James JPA Mail Server>> (deprecated)
 * <<test,James Test Server>>

Whichever one you pick, once it is up and running you will likely need to bring your existing emails into it:
xref:migrating.adoc[migrating existing data] is documented once for all the servers.

If you are just checking out James for the first time, then we highly recommend
investigating the servers in this order:

. Initiate yourself with James by using the <<demo,Demo Server>>
. Deploy the <<distributed,Distributed Server>>, or its <<postgres,Postgres variant>>

[#demo]
== James Demo Server
The xref:demo.adoc[Demo Server] is intended for those who just want 
to give James a quick spin on their local machine to see what all
the fuss is about.



[#distributed]
== James Distributed Mail Server 

The xref:distributed/index.adoc[*Distributed Server*] is a heavy-duty industrial
enterprise mail server.

This is the most feature-rich server, but also by far the most complex,
and is intended for experts only.



[#postgres]
== James Postgres Mail Server

The xref:postgres/index.adoc[*Distributed with Postgres Server*] is a one
variant of the distributed server with Postgres as the database.



[#jpa]
== James JPA Mail Server

The xref:jpa/index.adoc[*JPA Server*] is a single node server storing all its data within a
relational database, accessed through JPA.

*It is deprecated*: it is not actively maintained anymore, lacks major James features, and may be removed in a
future release. Use the <<postgres,Postgres Server>> instead.



[#test]
== James Test Server

The xref:test.adoc[*Test Server*] is, as the name suggests, for testing purposes.


[#migrating]
== Migrating to a James Server

Adopting a James Server, or moving from one variant to another, means copying the mailboxes of your users over.
That procedure relies on IMAP and impersonation, and is therefore identical for every server presented above. It
is documented in xref:migrating.adoc[Migrating existing data].
