= Apache James Mail Servers
:navtitle: Servers

James offers five types of ready-made Mail Servers. The servers are intended 
for those with different needs, ranging from xref:concepts:user/index.adoc#Operators[Operators]
who are interested in setting up a server for the first time, to experienced teams of 
xref:concepts:user/index.adoc#Developer[Developers]
looking to deploy an advanced distributed system.
Each of the servers has been tested and verified so you can 
deploy a production-grade 
xref:concepts/insert-link[Mail Server] with confidence.

The available James Servers are:

 * <<demo,James Demo Mail Server>>
 * <<basic,James Basic Mail Server>>
 * <<extendable,James Extendable Mail Server>>
 * <<distributed,James Distributed Mail Server>>
 * <<test,James Test Server>>

If you are just checking out James for the first time, then we highly recommend
investigating the servers in this order:

. Initiate yourself with James by using the <<demo,Demo Server>>
. Install the <<basic,Basic Server>>
. If and only if the Basic Server is not enough, then try the <<extendable,Extendable Server>>

[#demo]
== James Demo Server
The xref:demo.adoc[Demo Server] is intended for those who just want 
to give James a quick spin on their local machine to see what all
the fuss is about.



[#basic]
== James Basic Mail Server

If you just want to get up and running quickly, if you have very simple needs,
or you want to try deploying a mail server for the first time, then the
xref:basic/index.adoc[*Basic Server*] is the right choice for you. If you are
not sure which server you should be using, then this server is probably the right
choice.

This server is intended to be the simplest to set up and use in production.
It has the least amount of complexity and configurations to worry about.
The last thing you need is
to have to resolve difficult issues on a production server when you have not
yet acquired the requisite knowledge to deal with those issues. Using the
xref:basic/index.adoc[*Basic Server*] will help you reduce the risk of running into 
production issues.



[#extendable]
== James Extendable Mail Server

When your requirements start to get a little more serious, or you
start to feel adventurous and want to begin your own email adventure,
you can consider using the xref:extendable.adoc[*Extendable Server*].

This server is intended for experts who understand the consequences of
what they are doing. It provides extension mechanisms, configurations,
and integration points to customize its behavior. Unless you are processing
millions of emails on a daily basis (in which case you should consider the
<<distributed,Distributed Server>>), this server should cover just about
any email needs you may have.



[#distributed]
== James Distributed Mail Server 

The xref:distributed.adoc[*Distributed Server*] is a heavy-duty industrial 
enterprise mail server.

This is the most feature-rich server, but also by far the most complex,
and is intended for experts only.



[#test]
== James Test Server

The xref:test.adoc[*Test Server*] is, as the name suggests, for testing purposes.
