=== DLP

Enable evaluation of incoming emails against DLP rules (Data Leak Prevention) attached to the sender domains.

Example:

----
<mailet match="DLP" class="ToRepository">
   <repositoryPath>/var/mail/quarantine</repositoryPath>
</mailet>
----

Rules can be administered via xref:operate/webadmin.adoc#_administrating_dlp_configuration[webAdmin].

Only available on top of Memory and Cassandra storages.

Additionally a cache can be added to reduce queries done to the underlying database.

Example:

----
<mailet match="DLP=cache:60s" class="ToRepository">
   <repositoryPath>/var/mail/quarantine</repositoryPath>
</mailet>
----

Will query the DLP rules for a given domain only every 60 seconds.

Please note that querying DLP rules on top of Cassandra relies on Event sourcing, involves reading a potentially
large event stream and involves some SERIAL reads (LightWeight transactions) for each processed emails.

Efficiency of the cache can be tracked with the following metrics:

   - `dlp.cache.hitRate`
   - `dlp.cache.missCount`
   - `dlp.cache.hitCount`
   - `dlp.cache.size`