version: '3.0'

services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "25:25"
      - 143:143
      - 993:993
      - 465:465
    depends_on:
      - james

  james:
    image: apache/james:memory-latest
    container_name: james
    hostname: james.local
    command:
      - --generate-keystore
    volumes:
      - ./smtpserver.xml:/root/conf/smtpserver.xml:ro
      - ./imapserver.xml:/root/conf/imapserver.xml:ro

  helo:
    image: alpine:latest
    command: "ash -c 'apk add --update --no-cache netcat-openbsd && echo \"HELO example.local\" | nc haproxy 25'"
    depends_on:
      - haproxy