= Guice-Distributed Server How-to

== Requirements

 * Java 11 SDK

Third party compulsory dependencies:

 * Cassandra 4.0
 * OpenSearch 2.1.0
 * RabbitMQ-Management 3.8.18
 * Zenko Cloudserver or AWS S3

== Features Added:

* Restricted email sending to outside the org. e.g; <user>.<org>@<domain> can only send emails to other users with the same <org> and <domain>
* Added Gmail style "+ addressing". If your email is <user>@<domain>, you can use <user>\+<abc>@<domain> anywhere and still get your emails.
The server ignores any string following the "+" character until the "@" character.
(more details: https://eit.ces.ncsu.edu/2023/02/gmail-plus-addressing-the-hidden-feature-that-can-help-you-get-more-out-of-your-inbox/)
* Disabled all authentication methods except JWT Authentication (RS256). User creation no longer requires a password.
* Added a webadmin route for deleting an entire group. Example cURL command:
-----
$ curl --location --request DELETE 'http://ip:port/address/groups/myGroup'
-----


[source]

== Running the server method 1
-----

$ docker compose -f docker-composeOLD.yml up

-----

== Running the server method 2
-----

$ cd server/apps/distributed-app/

$ mvn clean install -DskipTests
 OR
$ mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort -Dsort.keepBlankLines -Dsort.predefinedSortOrder=custom_1 -DskipTests clean install

$ docker compose -f docker-compose.yml up -d

$ sudo (which java) -Dworking.directory=. -Dlogback.configurationFile=conf/logback.xml -Djdk.tls.ephemeralDHKeySize=2048 -jar target/james-server-distributed-app.jar --generate-keystore

-----

The [CLI](https://james.apache.org/server/manage-cli.html) can easily be used:


[source]
----
docker exec CONTAINER-ID james-cli ListDomains
----

Note that you can create a domain via an environment variable. This domain will be created upon James start:

[source]
----
--environment DOMAIN=domain.tld
----


[source]

== Send emails using telnet

```
telnet 127.0.0.1 25
EHLO spammer.com
MAIL FROM: <sender@spammer.com>
RCPT TO: <recipient@domain.tld>
DATA
Subject: This mail should be blocked

Is it?
.
quit
```

```
telnet 127.0.0.1 25
EHLO spammer.com
MAIL FROM: <another@spammer.com>
RCPT TO: <recipient@domain.tld>
DATA
Subject: This mail should be received

Is it?
.
quit
```
