Consult this link:{sample-configuration-prefix-url}/imapserver.xml[example] for guidance on how to configure IMAP.

The IMAP service is configured in the file `imapserver.xml`.
It contains one `imapservers` element that can contain multiple `imapserver` elements.

The `imapserver` element can be configured using the common options described xref:{pages-path}/configure/server.adoc[here].
Additional settings are described below.

.`imapserver` element
|===
| Property Name | Explanation

| `compress`
| Enables / Disables the IMAP COMPRESS extension
It is an optional boolean that defaults to `false`.

| `maxLineLength`
| Sets the maximal allowed line-length.
If a request is too long, a BAD response is returned to the client.
This should be set with caution as larger values make the server more susceptible for denial of service attacks.
If OIDC is used, it must be relative large as the encoded access tokens can become quite large.
It is an optional integer with a generous default of 65536.
The default should be enough for all applications, even when using OIDC.

| `inMemorySizeLimit`
| Sets a memory limit for incoming IMAP messages.
If a message is too large, it is streamed to a temporary file.
It is an optional value with a default of `10M` (10 mebibytes).
The last character of the value may be a unit.
Supported units are `B` for bytes, `K` for kibibyte (1,024 bytes), `M` for mebibyte (1,024 kibibytes), and `G` for gibibyte (1,024 mebibytes).
If no unit is given, the value is interpreted as bytes.

| `literalSizeLimit`
| Sets a hard size limit for IMAP literals and incoming IMAP messages.
If exceeded, an exception is thrown.
This value is communicated to the client via the IMAP APPENDLIMIT extension.
It is optional and defaults to 0 (unlimited).
Unit parsing is the same as with `inMemorySizeLimit` above.

| `timeout`
| Sets a timeout for connections.
If no read or write operations have been performed in this time, the connection is closed.
Optional integer in seconds that defaults to 1,800 (30 minutes).
The timeout can not be shorter than 30 minutes.

| `auth`
| Configures user authentication.
More details of this element are given below.

| `plainAuthDisallowed`
| Deprecated. If `auth.requireSSL` is not present, this is used as fallback.
It is an optional boolean that defaults to `true`.

| `ignoreIDLEUponProcessing`
| Disables sending heartbeats to the client while processing its request.
It is an optional boolean that defaults to `true`.

| `disabledCaps`
| Removes capabilities from the response of the IMAP CAPABILITY command.
This is an optional, pipe-separated list of strings.
By default, no capabilities are omitted.
Note that this only removes the capabilities from the response, it does not disable the capabilities!
It prevents standard-conformant clients from using commands that only work with the disabled capabilities but **it is not a security feature**.

| `enableIdle`
| Allows the client to request live updates via the IMAP IDLE command.
It is an optional boolean that defaults to `true`.

| `idleTimeInterval`
| Sets the interval in which the server sends heartbeats after the client issued an IDLE command.
If `enableIdle` is `false`, this has no effect.
It is an optinal integer that defaults to 120.

| `idleTimeIntervalUnit`
| Sets the unit of `idleTimeInterval`.
If `enableIdle` is `false`, this has no effect.
It is an optional value which must be a parseable `TimeUnit` and defaults to `SECONDS`.

| `maxQueueSize`
| Sets an upper bound for the IMAP throttler queue.
Requests that can not be queued are rejected and not executed.
It is an optional integer that defaults to 4,096.
A value of 0 disables the queue.

| `concurrentRequests`
| Sets the maximum number of IMAP requests that are executed simultaneously.
All requests past that limit are queued.
It is an optional Integer that defaults to 20.
A negative value deactivates this feature and leads to unbounded concurrency.

| `provisionDefaultMailboxes`
| Enables the provision of additional mailboxes.
By default, only `INBOX` is created.
If `true`, James additionally creates the mailboxes `Outbox`, `Sent`, `Trash`, `Drafts`, `Archive`, and `Spam` on first login of a user.
It is an optional boolean which defaults to `true`.

| `idCommandResponse`
| Configures the server response to the IMAP ID command.
It is an optional element containing up to 30 `field` elements.
Every `field` element must have the attributes `name` and `value`.
See RFC 2971 for more details.

|===

== Authentication

The `auth` element mentioned above has the following options.

.`auth` element
|===
| Property Name | Explanation

| `auth.plainAuthEnabled`
| Enables the authentication mechanisms `PLAIN` and `LOGIN`.
It is an optional boolean that defaults to `true`.

| `auth.requireSSL`
| Configures whether the authentication mechanisms `PLAIN` and `LOGIN` require a secure connection (TLS or STARTTLS).
It has no effect on other authentication mechanisms.
It also has no effect if `plainAuthEnabled` is `false`.
The value is optional.
If not configured, it uses the value of `plainAuthDisallowed` (which defaults to `true`) as fallback.

| `auth.adminUsers`
| Configures admin users that are authorized to impersonate any IMAP user.
It is an optional element containing `adminUser` elements.
**Do not configure this for publicly exposed IMAP servers!**

| `auth.oidc`
| Configures authentication via OIDC.
The configuration is described in more detail xref:{pages-path}/configure/oidc.adoc[here].

|===

== Traffic Shaping

Including a `trafficShaping` element enables an optional link:https://netty.io/4.0/api/io/netty/handler/traffic/ChannelTrafficShapingHandler.html[Netty traffic shaping handler].
This adds the following functionality:

- Recording per channel bandwidth consumption.
- Defining per channel bandwidth limit. This helps maintaining fairness and a good quality of service.

Example:

[source,xml]
----
<imapserver>
    <!-- ... -->
    <trafficShaping>
        <writeTrafficPerSecond>0</writeTrafficPerSecond>
        <readTrafficPerSecond>0</readTrafficPerSecond>
        <checkInterval>1000</checkInterval>
        <maxDelays>15000</maxDelays>
    </trafficShaping>
</imapserver>
----

All inner elements are optional.
The example above shows the default values.
The values are directly used for the instantiation of `io.netty.handler.traffic.ChannelTrafficShapingHandler`.

== Command Throttler

James ships an optional IMAP command throttler aimed at slowing down lower-quality clients that generate a high volume of requests.
It allows a different configuration for every command and is applied at the scope of an IMAP session.
The throttler is enabled by including a `perSessionCommandThrottling` element in the configuration.

For every command, the following configurations are available.

- `thresholdCount`: Throttling is enabled after the client issued the command `thresholdCount` number of times. It is a mandatory integer.
- `additionalDelayPerOperation`: After the threshold above has been reached, a delay is introduced. It is calculated as the number of previous occurrences of the command times `additionalDelayPerOperation`. This means that with a threshold of 25 and a delay of 2ms, the 26th occurrence of the command has a delay of 50ms. It is a mandatory duration with unit. The unit should be `ms` (millisecond) or `s` (second) in most cases.
- `observationPeriod`: After this time, the counter for the command is reset. This removes the delay. It is a mandatory duration with unit. The unit should be `s` (second) or `m` (minute) in most cases.
- `maxDelay`: The maximum delay for the command. It is a mandatory duration with unit. The unit should be `ms` (millisecond) or `s` (second) in most cases.
- `resetOn`: An different IMAP command that resets counter and delay for the command. It is an optional string. By default, no IMAP command triggers a reset.

Sample configuration:

[source,xml]
----
<imapserver>
  <!-- ... -->
  <perSessionCommandThrottling>
    <select>
      <thresholdCount>25</thresholdCount>
      <additionalDelayPerOperation>2ms</additionalDelayPerOperation>
      <observationPeriod>10m</observationPeriod>
      <maxDelay>1s</maxDelay>
      <resetOn>APPEND</resetOn> <!-- Allows a full refresh after sending an email. -->
    </select>
    <append>
      <thresholdCount>5</thresholdCount>
      <additionalDelayPerOperation>10ms</additionalDelayPerOperation>
      <observationPeriod>5m</observationPeriod>
      <maxDelay>2s</maxDelay>
    </append>
  </perSessionCommandThrottling>
</imapserver>
----

Note that commands are delayed prior to their execution and thus are not subject to the setting `concurrentRequests` until they are executed.

== Extending IMAP

IMAP decoders, processors and encoders can be customized.
You can xref:{pages-path}/customization/imap.adoc[read more here].

The following configuration properties are available for extensions:

.`imapserver` element
|===
| Property Name | Explanation

| `imapPackages`
| Configures which packages to load for IMAP.
IMAP packages bundle decoders (IMAP command parsing), command processors, and encoders.
The setting is optional and defaults to `org.apache.James.modules.protocols.DefaultImapPackage`.
The element must contain a Java classpath and can appear multiple times.
If configured, the union of all packages is used.
Remember to include `DefaultImapPackage` if you want to use its functionality.

| `additionalConnectionChecks`
| Configures an additional connection check.
A connection check decides whether the client IP of a connection is secure.
It must contain a Java classpath.
This element can be used multiple times.

| `customProperties`
| This element can be used to set an arbitrary property.
The value must have the form `key=value`.
This element can be used multiple times.
Using this enables configuring custom IMAP extensions without touching the code responsible for loading the configuration.

|===

== Auto-Configuration for Mail User Agents

Check link:https://github.com/apache/james-project/tree/master/examples/imap-autoconf[this example] for the auto-configuration of mail user agents.

== Local Cache for Partial Fetch

Some clients use partial fetch in order to emulate retriable downloads of individual body parts.
Therefore, we offer a way for James to cache the latest partially fetched message in the IMAP session.
This is done using a weak reference.

The following configuration options are available.

- `partialBodyFetchCacheEnabled`: Enables the cache. It is an optional boolean that defaults to `false`.
- `partialBodyFetchCacheDuration`: Configures how long partial bodies are cached. It is an optional integer with an optional unit. The default value is 2 minutes and the default unit is minute. The unit should be `s` (second) or `m` (minute) in most cases.
- `partialBodyFetchCacheSize`: Sets the size of the cache. It is an optional integer with an optional unit. The default value is 500 mebibyte and the default unit is byte. The unit should be `MiB` (mebibyte) or `GiB` (gibibyte) in most cases.

Example with the default values:

[source,xml]
----
<imapserver>
  <partialBodyFetchCacheEnabled>false</partialBodyFetchCacheEnabled>
  <partialBodyFetchCacheDuration>2m</partialBodyFetchCacheDuration>
  <partialBodyFetchCacheSize>500MiB</partialBodyFetchCacheSize>
</imapserver>
----
