James servers are able to evaluate and execute Sieve scripts.

Sieve is an extensible mail filtering language. It's limited
expressiveness (no loops or variables, no tests with side
effects) allows user created scripts to be run safely on email
servers. Sieve is targeted at the final delivery phase (where
an incoming email is transferred to a user's mailbox).

The following Sieve capabilities are supported by Apache James:

  - link:https://www.ietf.org/rfc/rfc2234.txt[RFC 2234 ABNF]
  - link:https://www.ietf.org/rfc/rfc2244.txt[RFC 2244 ACAP]
  - link:https://www.ietf.org/rfc/rfc2298.txt[RFC 2298 MDN]
  - link:https://tools.ietf.org/html/rfc5228[RFC 5228 Sieve]
  - link:https://tools.ietf.org/html/rfc4790[RFC 4790 IAPCR]
  - link:https://tools.ietf.org/html/rfc5173[RFC 5173 Body Extension]
  - link:https://datatracker.ietf.org/doc/html/rfc5230[RFC 5230 Vacations]

To be correctly executed, please note that the *Sieve* mailet is required to be positioned prior the
*LocalDelivery* mailet.

== Managing Sieve Scripts

A user willing to manage his Sieve scripts on the server can do so via several means:

He can ask an admin to upload his script via the xref:{pages-path}/operate/cli.adoc[CLI]

As James supports ManageSieve (link:https://datatracker.ietf.org/doc/html/rfc5804[RFC-5804]) a user
can thus use compatible software to manage his Sieve scripts.</p>

== ManageSieve Protocol

*WARNING*: Support for the ManageSieve protocol should be considered experimental.

Consult this link:{sample-configuration-prefix-url}/managesieveserver.xml[example] for guidance on how to configure ManageSieve.

The ManageSieve service is configured in the file `managesieveserver.xml`.
It contains one `managesieveservers` element that can contain multiple `managesieveserver` elements.

The `managesieveserver` element can be configured using the common options described xref:{pages-path}/configure/server.adoc[here].

Additionally, it can contain an optional `oidc` element.
The OIDC configuration is described xref:{pages-path}/configure/oidc.adoc[here].
