The servers
xref:{pages-path}/configure/smtp.adoc[SMTP],
xref:{pages-path}/configure/pop3.adoc[POP3],
xref:{pages-path}/configure/imap.adoc[IMAP], and
xref:{pages-path}/configure/sieve.adoc[Managesieve]
support TLS.
The configuration is the same for all of them and this document explains how to do it.

== Configure a Server to Use TLS

As described in xref:{pages-path}/configure/server.adoc[SMTP],
there is a `tls` element inside the XML server element.

It supports two attributes:

- `socketTLS`: Enables STARTTLS for this server. The client can upgrade the connection using the `STARTTLS` command.
- `startTLS`: Enables implicit TLS on this port.

By default, both attributes are `false`.
However, it is highly recommended to use TLS and set one of these to `true` for every server.
They can not both be `true` for one server.

Additionally, the `tls` element can have the following child elements.
There are also examples after the table.

.`tls` element
|===
| Property Name | Explanation

| `supportedCipherSuites`
| Contains the ciphersuites that should be enabled.
Every ciphersuite is in its own `cipherSuite` element.
If not configured, the library's default is used.

| `supportedProtocols`
| Contains the protocols that should be enabled.
Every protocol is in its own `protocol` element.
If not configured, the library's default is used.

| `keystore`
| The path to a keystore.
The keystore **must** have only one certificate.
Either the keystore or both private key and certificates must be configured.

| `keystoreType`
| The type of the keystore.
It is an optinal string with the default value `JKS`.
A common alternative is `PKCS12`.

| `privateKey`
| The path to a private key.
If configured, `certificates` must also be configured.

| `certificates`
| A path to a certificate bundle.
The last certificate in the bundle is the one signed by a root CA.
If configured, `privateKey` must also be configured.

| `secret`
| A secret for the keystore or private key.
It is optional.

| `clientAuth`
a| Configures TLS client authentication.
If this is present, all clients are required to authenticate on the TLS level.
It has the following child elements:

- `clientAuth.truststore`: An optional path to the truststore for verifying client certificates. The truststore can contain client certificates directly or CAs that issued client certificates. If not configured, the library's default is used.
- `clientAuth.truststoreType`: The type of the keystore. It is optional and defaults to `JKS`.
- `clientAuth.truststoreSecret`: An optional secret for the truststore.

| `enableOCSPCRLChecks`
| Enables revocation checks for client authentication.
It is an optional boolean that is `false` by default.

| `sessionCache.size`
| Sets the maximum number of TLS sessions in the session cache.
If not configured, the library's default is used.

| `sessionCache.timeout`
| Sets the duration after which TLS sessions in the cache time out.
If not configured, the library's default is used.
It is an integer followed by an optional unit.
The default unit is `ms` (millisecond) and other reasonable values are `s` (second) or `m` (minute).

|===

The paths in the table above are usually file paths and prefixed with `file://`.
They can either be relative (e.g., `file://conf/imap.crt`) or absolute (e.g., `file:///james/conf/imap.crt`).

== TLS for Email Services

Email was established before protocols like TLS that can secure TCP connections independent of the application layer.
Therefore, the email services on the initially established ports never had a security layer.
Because of backward compatibility, this will not change.
STARTTLS was introduced to negotiate a security layer over the insecure channel.
For it to work, both the server and the client must abort sessions if STARTTLS is not used.

Alternatively, other ports that are expected to use implicit TLS have been established by RFC 8314.

.Ports for email services
|===
| Service | Client | Ports

| SMTP
| Remote MX
| insecure: 25, TLS: not defined by RFC

When trying to deliver emails to another email server using implicit TLS, James attempts to use port 465.

| SMTP Submission
| MUA
| insecure: 587, TLS: 465

| IMAP
| MUA
| insecure: 143, TLS: 993

| POP3
| MUA
| insecure: 110, TLS: 995

| LMTP
| Local MX
| insecure: 24, no TLS port defined by RFC

|===

As all modern email clients support TLS nowadays, there is no need to offer SMTP submission, IMAP, or POP3 without implicit TLS.
In most cases, it should suffice to offer only one version with implicit TLS for each of these services.

As the MX DNS record only resolves to an IP, other email servers can not know whether the other server offers SMTP with implicit TLS and on which port.
Every email server **must** therefore offer SMTP on port 25.
You may choose to additionally offer SMTP with implicit TLS on port 465 as some email servers (e.g., James) also try that endpoint.
Note that you need to move the SMTP submission service with implicit TLS to another port in that case (this works well as it is only used by MUAs).

As James does not support authentication for LMTP,
the port **must only be exposed** to the local SMTP server that uses it.

**We strongly recommend that you enable STARTTLS for all services that you choose to offer without implicit TLS.**

== Examples

=== JKS with Password

[source,xml]
....
<tls socketTLS="false" startTLS="true">
  <keystore>file://conf/keystore</keystore>
  <secret>yoursecret</secret>
</tls>
....

=== PKCS12 Keystore with Password

[source,xml]
....
<tls socketTLS="false" startTLS="true">
  <keystore>file://conf/keystore</keystore>
  <keystoreType>PKCS12</keystoreType>
  <secret>yoursecret</secret>
</tls>
....

=== Certificates and Private Key as PEM Files

[source,xml]
....
<tls socketTLS="true" startTLS="false">
  <privateKey>file://conf/imap.key</privateKey>
  <certificates>file://conf/imap.crt</certificates>
</tls>
....

=== Certificates and Private Key with Password as PEM Files

[source,xml]
....
<tls socketTLS="true" startTLS="false">
  <privateKey>file://conf/imap.key</privateKey>
  <certificates>file://conf/imap.crt</certificates>
  <secret>yoursecret</secret>
</tls>
....

=== Explicitly Selected Protocol Versions and Ciphersuites

**Note:** Only modify the following settings if you know exactly what you are doing.
The configuration below is extremely insecure.

[source,xml]
....
<tls socketTLS="true" startTLS="false">
  <supportedProtocols>
    <protocol>TLSv1.2</protocol>
    <protocol>TLSv1.1</protocol>
    <protocol>TLSv1</protocol>
    <protocol>SSLv3</protocol>
  </supportedProtocols>
  <supportedCipherSuites>
    <cipherSuite>TLS_AES_256_GCM_SHA384</cipherSuite>
    <cipherSuite>TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256</cipherSuite>
  </supportedCipherSuites>
  <!-- ... -->
</tls>
....

=== TLS Session Cache

TLS session resumption allows clients to reconnect without performing a full TLS handshake, reducing CPU usage and connection latency.
James caches completed TLS sessions server-side using the JDK `SSLSessionContext`.

[source,xml]
....
<tls socketTLS="false" startTLS="true">
  <keystore>file://conf/keystore</keystore>
  <keystoreType>PKCS12</keystoreType>
  <secret>yoursecret</secret>

  <sessionCache>
    <size>1024</size>
    <timeout>600s</timeout>
  </sessionCache>
</tls>
....

When a cached session is found, the client and server skip the asymmetric key exchange and certificate verification,
reusing the previously negotiated symmetric keys. This is particularly effective for email clients that open many
short-lived connections (e.g., mobile push sync).

=== Client Authentication

When you enable TLS, you may also configure the server to require a client certificate for authentication.

[source,xml]
....
<tls socketTLS="false" startTLS="true">
  <keystore>file://conf/keystore</keystore>
  <keystoreType>JKS</keystoreType>
  <secret>yoursecret</secret>

  <clientAuth>
    <truststore>file://conf/truststore</truststore>
    <truststoreType>JKS</truststoreType>
    <truststoreSecret>yoursecret</truststoreSecret>
  </clientAuth>
  <enableOCSPCRLChecks>false</enableOCSPCRLChecks>
</tls>
....

== Certificates by Well-Known Root CA (Preferred)

In order for MUAs and other email servers to trust the certificates by your email server out of the box, they need to be issued (at least transitively) by a trusted root CA.
The easiest and cheapest way to get such a certificate is by using ACME.

We recommend to use either RSA (with at least 4,096 bits key size) or ECDSA as signature algorithm.
Those may not provide the best security but they are the algorithms with the best support among MUAs and MXs.
The tools presented below choose a reasonable default so you do not have to configure the algorithm at all.

Although most ACME clients are built for requesting certificates for websites,
you can easily use them to request certificates for an email server.
Some ACME clients that work well are Caddy and certbot.
You must only be able to set up an ACME client to listen on port 80 on the domain you want a certificate for.

A Caddy server with the following configuration file obtains a certificate for the domain `imap.example.internal`.

.Caddyfile
[source]
....
{
	email <Email address for Let's Encrypt>
	events {
		on cert_obtained exec cert-hook.sh {event.data.identifier} {event.data.private_key_path} {event.data.certificate_path}
	}
}

imap.example.internal {
	respond 204
}
....

With certbot, you can use the command

[source]
....
certbot certonly \
  -c config.ini \
  --non-interactive \
  --cert-name imap \
  --domains imap.example.internal \
  --keep-until-expiring \
  --deploy-hook 'imap-deploy-hook.sh'
....

with the following config file to obtain a certificate for the same domain.

[source]
....
email = <Email address for Let's Encrypt>
agree-tos = true
authenticator = standalone
preferred-challenges = http
....

=== Automatic Certificate Renewal

As long as Caddy runs, it refreshes the certificate.
With a link:https://github.com/mholt/caddy-events-exec[plugin], Caddy can automatically execute a script after obtaining a new certificate.

The solution with certbot requires you to execute the command regularly to refresh the certificate.
Using the deploy hook argument, a script can be executed after a certificate has been obtained.

These hooks should be used to make James aware of the new certificate.
First, the PEM files for private key and certificate must be copied to the path configured in James.
Afterward, James can be triggered to reload its certificates by POSTing to the `/servers?reload-certificate` endpoint of the webadmin API.

== Creating your own PEM Keys

This approach should only be used during development.
The certificate will not be accepted by MUAs or other email servers.

The following commands can be used to create a self-signed PEM certificate:

[source]
....
# Generate a private key.
openssl genpkey -outform pem -out imap.key -algorithm rsa -pkeyopt rsa_keygen_bits:4096

# Create a self-signed certificate.
# Note that this is missing the SAN extension and is therefore not compliant to RFC 9525.
openssl x509 -new -set_subject '/CN=imap.example.internal' -key imap.key -keyform pem -outform pem -out imap.crt
....

You may then supply this TLS configuration:

[source,xml]
....
<tls socketTLS="true" startTLS="false">
  <privateKey>file://conf/imap.key</privateKey>
  <certificates>file://conf/imap.crt</certificates>
</tls>
....

== Keystores

Keystores can be managed using the `keytool` utility which is included in the JDK.
It is possible to load certificates in the keystore that have been obtained by a trusted CA.

The following approach shows how to create a keystore with a self-signed certificate and should only be used during development.
The certificate will not be accepted by MUAs or other email servers.

The following command creates a keystore with a self-signed certificate:

[source]
....
keytool \
  -alias imap \
  -genkeypair -keyalg rsa -keysize 4096 \
  -storetype pkcs12 -keystore keystore.p12 -storepass yoursecret \
  -dname 'CN=imap.example.internal' \
  -ext san=dns:imap.example.internal
....

You may then supply this TLS configuration:

[source,xml]
....
<tls socketTLS="true" startTLS="false">
  <keystore>file://conf/keystore.p12</keystore>
  <keystoreType>PKCS12</keystoreType>
  <secret>yoursecret</secret>
</tls>
....
