version: '3.0'

# Explanation:
# - starts a haproxy server on address haproxy:25 that forwards connections to james:2525
# - the service "helo" just sends a HELO to haproxy that will be forwarded to james
# - james receives the origin ip address of the helo container provided by haproxy
# - you can also use telnet to connect to haproxy if you expose haproxy's port 25
#
# Caveat: james might take a while to start. Thus start james first,
# then haproxy and finally helo. Observe the log ouput of the helo
# container to see if it works correctly.

services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - james

  james:
    image: apache/james:jpa-smtp-latest
    container_name: james
    hostname: james.local
    volumes:
      - ./smtpserver.xml:/root/conf/smtpserver.xml:ro

  helo:
    image: alpine:latest
    #command: "echo 'HELO example.local' | nc -v -lk haproxy 25 -e "
    command: "ash -c 'apk add --update --no-cache netcat-openbsd && echo \"HELO example.local\" | nc haproxy 25'"
    depends_on:
      - haproxy