version: '3'

services:

  james:
    depends_on:
      - graphite
    image: apache/james:memory-latest
    container_name: james
    hostname: james.local
    command:
      - --generate-keystore
    volumes:
      - ./target/metrics-graphite-jar-with-dependencies.jar:/root/extensions-jars/metrics-graphite.jar
      - ./james/extensions.properties:/root/conf/extensions.properties

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
