= Simple Mail Transfer Protocol (SMTP)
:navtitle: SMTP

== Overview

When the original specification for Simple Mail Transfer Protocol, or SMTP, 
was published almost 40 years ago together with 
xref:messages/imf.adoc[IMF], email as we know it today was born.



== Specifications

=== RFC821

https://tools.ietf.org/html/rfc821[RFC821] ("Simple Mail Transfer Protocol")
was the original SMTP specification published in 1982. 
It was obsoleted by <<RFC2821>> in 2001.

=== RFC2821

https://tools.ietf.org/html/rfc2821[RFC2821] ("Simple Mail Transfer Protocol") replaced
<<RFC821>>. It was itself replaced by <<RFC5321>> in 2008.

=== RFC 5321

https://tools.ietf.org/html/rfc5321[RFC5321] is the currently used standard for
"Simple Mail Transfer Protocol", or "SMTP". It is "a specification of the basic 
protocol for Internet electronic mail transport". If you are interested in all
the gory details, we recommend that you read this document.

This specification has many dependencies with xref:messages/imf.adoc[IMF],
xref:messages/mime.adoc[MIME], and other technical concepts, which can quickly
become utterly confusing.
Here, we provide a very short and simplified description of those portions of the 
specification that we felt were interesting enough to repeat here.

As the spec mentions, "SMTP transports a mail object",  a mail object being described
as an object that contains both an envelope and content. An SMTP client connects
to a server and communicates via a session. Both client and server provide a
mail transport service, and are therefore act as "Mail Transfer Agents", or
"MTAs". A mail originates and terminates with a "Mail User Agent" ("MUA").
On the originating side, a MUA may, for instance, collect mail to be transmitted
by a user and hand it off to an MTA. On the terminating side, an MTA would 
hand a mail off to an MUA.

"SMTP sessions are stateful, with both parties carefully maintaining a
common view of the current state." The session is initiated by the client,
which establishes a two-way channel to an SMTP server. The session must either
close successful (or with a failure message), else delivery is considered to
have failed.



== Related Concepts

SMTP relates to:

 * *xref:messages/index.adoc[Email messages]*, in that the SMTP protocol exists to transfer
   messages from one host to another
 * *MTA*, in that the very nature of SMTP is about specifying how a message
   gets transferred from one MTA to another


== James Model

(TODO: explain how all this is modeled in James)




== Try It!

Add a section to the demo, and connect manuall via an SMTP session


