{{- if .Values.adminIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: james-admin
  {{- with .Values.adminIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.adminIngress.ingressClassName }}
  ingressClassName: {{ .Values.adminIngress.ingressClassName }}
{{- end }} 
{{- if .Values.adminIngress.tls }}
  tls:
  - hosts:
    - {{ .Values.dns.adminUrl }}
    {{ toYaml .Values.adminIngress.tls }}
{{- end }}    
  rules:
  - host: {{ .Values.dns.adminUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: james-admin
            port:
              number: 8000
{{- end }}
