{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jmap
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.dns.jmapUrl }}
    {{ toYaml .Values.ingress.tls }}
{{- end }}    
  rules:
  - host: {{ .Values.dns.jmapUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jmap
            port:
              number: 80
{{- end }}
