apiVersion: v1
data:
  jwt_publickey: "{{ .Values.james.secret.jwtPublicKey | b64enc }}"
  jwt_privatekey: "{{ .Values.james.secret.jwtPrivateKey | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: james-jwt-key
---
apiVersion: v1
data:
  james-user: "{{ .Values.james.secret.cassandraUser | b64enc }}"
  james-password: "{{ .Values.james.secret.cassandraPassword | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: db-cassandra-account-james
---
{{- if and (.Values.james.secret.esUser) (.Values.james.secret.esPassword) }}
apiVersion: v1
data:
  james-user: "{{ .Values.james.secret.esUser | b64enc }}"
  james-password: "{{ .Values.james.secret.esPassword | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: db-es-account-james
{{- end }}
---
apiVersion: v1
data:
  dkim.key: "{{ .Values.james.secret.dkimPrivateKey | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: dkim-private-key 
---
apiVersion: v1
data:
  OS_S3_ENDPOINT: {{ .Values.james.secret.s3.endpoint | b64enc }}
  OS_S3_REGION: {{ .Values.james.secret.s3.region | b64enc }}
  OS_S3_ACCESSKEYID: {{ .Values.james.secret.s3.accessKeyId | b64enc }}
  OS_S3_SECRETKEY: {{ .Values.james.secret.s3.secretKey | b64enc }}
kind: Secret
type: Opaque
metadata:
  name: s3-james-credentials
---
apiVersion: v1
data:
  rabbitmq-user: "{{ .Values.rabbitmq.secret.jamesUser | b64enc }}"
  rabbitmq-password: "{{ .Values.rabbitmq.secret.jamesPassword | b64enc }}"
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-account-james
