= James Basic Mail Server
:navtitle: Basic 

The **James Basic Server** is intended for xref:concepts:user/index.adoc#Operator[Operators]
who are just getting initiated with operating their own 
xref:concepts/???[Self-Hosted] mail server.

The server is intended to be a mostly "out-of-the-box" solution.
With a few small interactions necessary to configure the system, you should
be up and running in no time with all the standard features.

These documents will present all the concepts that underpin this server,
and will walk you through its installation and configuration. If you run into
trouble, we explain how you can get help from the James Community.

 * xref:basic/context.adoc[The context of contemporary email]
 * xref:basic/objectives.adoc[Objectives and motivation of the Basic Server]
 * xref:basic/concepts.adoc[Useful background concepts]
 * xref:basic/architecture.adoc[Overview of architecture]
 * xref:basic/conf/index.adoc[Configuration]
 * xref:basic/help.adoc[Where to go for help]
