{
 "title": "James / BlobStore",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "blobStore:saveBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "blobStore:saveBytes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "blobStore:saveBytes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "blobStore:saveBytes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "blobStore:saveBytes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "blobStore:readBytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStore:readBytes{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:readBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStore:readBytes{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:readBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStore:readBytes{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:readBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStore:readBytes{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:readBytes\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "blobStore:delete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "blobStore:delete{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "blobStore:delete{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "blobStore:delete{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "blobStore:delete{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "blobStore:CacheLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreCacheLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:saveBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreCacheLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:saveBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreCacheLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:saveBytes\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreCacheLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:saveBytes\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "blobStore:CacheHits/CacheMisses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blobStoreCacheHits_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "CacheHits total"
    },
    {
     "expr": "blobStoreCacheMisses_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "CacheMisses Total"
    }
   ]
  },
  {
   "title": "blobStore:BackEndLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreBackEndLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:delete\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreBackEndLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:delete\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreBackEndLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:delete\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "blobStoreBackEndLatency{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"blobStore:delete\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}