{
 "title": "James / IMAP Count Board",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IMAP Connections total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "imapConnections_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Connections",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"imapConnections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-CAPABILITY",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CAPABILITY_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_CAPABILITY",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CAPABILITY\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-FETCH",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_FETCH_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_FETCH",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-FETCH\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-SELECT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_SELECT_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_SELECT",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-SELECT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-IDLE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_IDLE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_IDLE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-IDLE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-STORE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_STORE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_STORE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-STORE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LSUB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LSUB_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_LSUB",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LSUB\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-AUTHENTICATE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_AUTHENTICATE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_AUTHENTICATE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-AUTHENTICATE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-NAMESPACE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_NAMESPACE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_NAMESPACE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-NAMESPACE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-GETQUOTAROOT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_GETQUOTAROOT_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_GETQUOTAROOT",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-GETQUOTAROOT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LIST",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LIST_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_LIST",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LIST\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-CLOSE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CLOSE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_CLOSE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CLOSE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-NOOP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_NOOP_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_NOOP",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-NOOP\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LOGIN",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "max(IMAP_LOGIN_count{instance=\"$WebAdmin\", job=\"Apache James\"})",
     "legendFormat": "IMAP_LOGIN",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGIN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LOGOUT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGOUT_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_LOGOUT",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGOUT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-APPEND",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_APPEND_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_APPEND",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-APPEND\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-CREATE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CREATE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_CREATE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CREATE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-COPY",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_COPY_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_COPY",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-COPY\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-MOVE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_MOVE_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "IMAP_MOVE",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-MOVE\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}