{
 "title": "James / IMAP board",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "IMAP Connections total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "imapConnections_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Connections",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"imapConnections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LOGIN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGIN{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGIN\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGIN{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGIN\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGIN{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGIN\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGIN{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGIN\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-CAPABILITY",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CAPABILITY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CAPABILITY\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_CAPABILITY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_CAPABILITY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_CAPABILITY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-AUTHENTICATE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_AUTHENTICATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-AUTHENTICATE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_AUTHENTICATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_AUTHENTICATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_AUTHENTICATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-SELECT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_SELECT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-SELECT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_SELECT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-SELECT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_SELECT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-SELECT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_SELECT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-SELECT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-GETQUOTAROOT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_GETQUOTAROOT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-GETQUOTAROOT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_GETQUOTAROOT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-GETQUOTAROOT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_GETQUOTAROOTIMAP_LIST{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-GETQUOTAROOT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_GETQUOTAROOT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-GETQUOTAROOT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-FETCH",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_FETCH{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-FETCH\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_FETCH{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-FETCH\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_FETCH{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-FETCH\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_FETCH{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-FETCH\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-APPEND",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_APPEND{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-APPEND\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_APPEND{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_APPEND{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_APPEND{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-IDLE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_IDLE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-IDLE\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_IDLE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-IDLE\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_IDLE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-IDLE\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_IDLE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-IDLE\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-NOOP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_NOOP{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-NOOP\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_NOOP{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_NOOP{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_NOOP{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-STORE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_STORE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-STORE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_STORE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}"
    },
    {
     "expr": "IMAP_STORE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}"
    },
    {
     "expr": "IMAP_STORE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "IMAP-LSUB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LSUB{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LSUB\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_LSUB{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_LSUB{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_LSUB{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-NAMESPACE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_NAMESPACE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-NAMESPACE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_NAMESPACE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_NAMESPACE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_NAMESPACE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-CLOSE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CLOSE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CLOSE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_CLOSE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}"
    },
    {
     "expr": "IMAP_CLOSE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}"
    },
    {
     "expr": "IMAP_CLOSE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "IMAP-LOGOUT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGOUT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGOUT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGOUT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGOUT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGOUT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGOUT\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LOGOUT{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LOGOUT\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-LIST",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LIST{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LIST\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LIST{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LIST\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LIST{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LIST\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_LIST{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-LIST\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IMAP-CREATE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_CREATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-CREATE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_CREATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_CREATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_CREATE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-COPY",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_COPY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-COPY\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_COPY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_COPY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "IMAP_COPY{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "IMAP-MOVE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "IMAP_MOVE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"IMAP-MOVE\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "IMAP_MOVE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}"
    },
    {
     "expr": "IMAP_MOVE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}"
    },
    {
     "expr": "IMAP_MOVE{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}"
    }
   ]
  }
 ]
}