{
 "title": "James / MATCHER",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "All",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "All{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"All\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "spoolProcessing",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "spoolProcessing{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"spoolProcessing\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SMTPAuthSuccessful",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTPAuthSuccessful{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTPAuthSuccessful\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RecipientIsLocal",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "RecipientIsLocal{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"RecipientIsLocal\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "HasMailAttribute",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "HasMailAttribute{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"HasMailAttribute\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}