{
 "title": "James / MailQueue",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "enqueuedMail:spool_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "enqueuedMail:spool_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "spool_total"
    }
   ]
  },
  {
   "title": "dequeuedMail:spool_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dequeuedMail:spool_total{instance=\"$WebAdmin\",job=\"Apache James\"}\n",
     "legendFormat": "spool_total"
    }
   ]
  },
  {
   "title": "enqueueMailTime:spool_total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "enqueueTime:spool{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "enqueueTime:spool{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "enqueueTime:spool{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "enqueueTime:spool{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "enqueuedMails:outgoing_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "enqueuedMail:outgoing_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "outgoing_total"
    }
   ]
  },
  {
   "title": "dequeuedMails:outgoing_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dequeuedMail:outgoing_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "outgoing_total"
    }
   ]
  },
  {
   "title": "enqueueMailTime:outgoing_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "enqueueTime:outgoing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "enqueueTime:outgoing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "enqueueTime:outgoing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "enqueueTime:outgoing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "spoolProcessing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spoolProcessing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "spoolProcessing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "spoolProcessing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "spoolProcessing{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "localDeliveredMails total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "localDeliveredMails_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "localDeliveredMails total"
    }
   ]
  }
 ]
}