{
 "title": "James / JMAP board",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "JMAP-request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_request{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-request\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_request{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_request{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_request{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-getMailboxes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_getMailboxes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-getMailboxes\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_getMailboxes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_getMailboxes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_getMailboxes{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-getMessageList",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_getMessageList{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-getMessageList\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_getMessageList{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_getMessageList{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_getMessageList{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-getMessages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_getMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-getMessages\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_getMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_getMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_getMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-SetMessageDestructionProcessor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_SetMessageDestructionProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-SetMessageDestructionProcessor\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_SetMessageDestructionProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_SetMessageDestructionProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_SetMessageDestructionProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-SetMessagesUpdateProcessor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_SetMessagesUpdateProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-SetMessagesUpdateProcessor\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_SetMessagesUpdateProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_SetMessagesUpdateProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_SetMessagesUpdateProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-SetMessageCreationProcessor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_SetMessageCreationProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-SetMessageCreationProcessor\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_SetMessageCreationProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_SetMessageCreationProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_SetMessageCreationProcessor{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-setMessages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_setMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-setMessages\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_setMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_setMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_setMessages{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-SetMailboxesDestructionProcessor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "JMAP_SetMailboxesDestructionProcessor"
    }
   ]
  },
  {
   "title": "JMAP-SetMailboxesCreationProcessor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "JMAP_SetMailboxesCreationProcessor"
    }
   ]
  },
  {
   "title": "JMAP-SetMailboxesUpdateProcessor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "JMAP_SetMailboxesUpdateProcessor"
    }
   ]
  },
  {
   "title": "JMAP-setMailboxes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_setMailboxes",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-setMailboxes\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-getVacationResponse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_getVacationResponse{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-getVacationResponse\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_getVacationResponse{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_getVacationResponse{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_getVacationResponse{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-setVacationResponse",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_setVacationResponse",
     "legendFormat": "quantile: {{quantile}}",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-setVacationResponse\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-mailboxes-provisioning",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_mailboxes_provisioning{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-mailboxes-provisioning\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_mailboxes_provisioning{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_mailboxes_provisioning{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_mailboxes_provisioning{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-user-provisioning",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_user_provisioning",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-user-provisioning\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-upload-post",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_upload_post",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-upload-post\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-download-post",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_download_post",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-download-post\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-download-get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_download_get",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-download-get\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "JMAP-authentication-post",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_authentication_post{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-authentication-post\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_authentication_post{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_authentication_post{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_authentication_post{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "JMAP-authentication-filter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "JMAP_authentication_filter{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"JMAP-authentication-filter\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "JMAP_authentication_filter{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "JMAP_authentication_filter{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "JMAP_authentication_filter{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}