{
 "title": "James / James JVM",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OpenFileDescriptor Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_file_descriptor{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "file descriptor",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"jvm.file.descriptor\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Threads Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_threads_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Threads count",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"jvm.threads.count\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_threads_deadlock_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Deadlock count",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"jvm.threads.deadlock.count\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_total_used{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Total memory used",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.total.max\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_total_max{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Total memory max",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.total.used\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_heap_used{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Heap Used",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.heap.max\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_heap_max{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Heap Max",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.heap.used\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "jvm_memory_heap_committed{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Heap Committed"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_non_heap_used{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Non heap used",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.non-heap.max\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_memory_non_heap_max{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Non heap max",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.memory.non-heap.used\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Class Loading",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_class_loading_loaded{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Loaded",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.class.loading.loaded\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_class_loading_unloaded{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Unloaded",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"jvm.class.loading.unloaded\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_gc_G1_Young_Generation_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Gc count",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"jvm.gc.count\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "jvm_gc_G1_Young_Generation_time{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "GC Time",
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"jvm.gc.time\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}