{
 "title": "James / SMTP board",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "SMTP Connections total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "smtpConnections_total{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "Connection total",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      }
     ],
     "query": "name:\"smtpConnections\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SMTP-ehlo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "SMTP_ehlo{instance=\"$WebAdmin\",job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"SMTP-ehlo\"",
     "timeField": "@timestamp"
    },
    {
     "expr": "SMTP_ehlo{instance=\"$WebAdmin\",job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "SMTP_ehlo{instance=\"$WebAdmin\",job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "SMTP_ehlo{instance=\"$WebAdmin\",job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "SMTP-quit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SMTP_quit{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "SMTP_quit{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "SMTP_quit{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "SMTP_quit{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "SMTP-data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SMTP_DATA{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "SMTP_DATA{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "SMTP_DATA{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "SMTP_DATA{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "SMTP-rcpt",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SMTP_rcpt{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "SMTP_rcpt{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "SMTP_rcpt{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "SMTP_rcpt{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "SMTP-mail",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "SMTP_mail{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "SMTP_mail{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "SMTP_mail{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "SMTP_mail{instance=\"$WebAdmin\", job=\"Apache James\", quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}