{
 "title": "James / JAMES DNS dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WebAdmin",
    "query": {
     "query": "label_values(smtpConnections_total, instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Get By Name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getByName\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get All By name",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.5\"}",
     "legendFormat": "p50",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.75\"}",
     "legendFormat": "p75",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.95\"}",
     "legendFormat": "p95",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.98\"}",
     "legendFormat": "p98",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.99\"}",
     "legendFormat": "p99",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName{instance=\"$WebAdmin\",job=\"Apache James\",quantile=\"0.999\"}",
     "legendFormat": "p999",
     "metrics": [
      {
       "field": "p99",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p50",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p75",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "p95",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get By Name Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getByName_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "getByName count",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "5",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"getByName\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get All By name Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "getAllByName_count{instance=\"$WebAdmin\",job=\"Apache James\"}",
     "legendFormat": "getAllByName count",
     "metrics": [
      {
       "field": "count",
       "id": "1",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "name:\"getAllByName\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}