=== Expires

Sanitizes or adds an expiration date to a message, in the form of an `Expires`
header (RFC 4021).

The mailet can force an existing expiration date to be within the bounds
given by `minAge`, `maxAge`, or both. `minAge` specifies the minimum time
the date must lie in the future, while `maxAge` specifies a maximum.

If a message has no expiration date, the mailet can add one according to
the optional `defaultAge` parameter.

All parameter values should be expressed in the following format: `Nunit`.
`N` should be positive. `unit` could be either in the short form
(`h`, `d`, `w`, `y` etc.), or in the long form (`hours`, days`, `weeks`,
`months`, `years`). The default unit is `days`.

Sample configuration:

....
<mailet match="All" class="Expires">
    <minAge>12h</minAge>
    <defaultAge>7d</defaultAge>
    <maxAge>8w</maxAge>
</mailet>
....

By itself the `Expires` header is informational only. But some variants of James
will let you delete expired messages through the 
xref:distributed/operate/webadmin.adoc#_administrating_messages[WebAdmin] interface:

....
curl -XDELETE http://ip:port/messages?byExpiresHeader
....
