= Postgresql James Server &mdash; opensearch.properties
:navtitle: opensearch.properties

:sample-configuration-prefix-url: https://github.com/apache/james-project/blob/postgresql/server/apps/postgres-app/sample-configuration
:pages-path: postgres
:server-name: Postgresql James server
include::partial$configure/opensearch.adoc[]

== Search overrides

*Search overrides* allow resolution of predefined search queries against alternative sources of data
and allow bypassing OpenSearch. This is useful to handle most resynchronisation queries that
are simple enough to be resolved against Postgres.

Possible values are:

- `org.apache.james.mailbox.postgres.search.AllSearchOverride` Some IMAP clients uses SEARCH ALL to fully list messages in
a mailbox and detect deletions. This is typically done by clients not supporting QRESYNC and from an IMAP perspective
is considered an optimisation as less data is transmitted compared to a FETCH command. Resolving such requests against
Postgresql is enabled by this search override and likely desirable.
- `org.apache.james.mailbox.postgres.search.UidSearchOverride`. Same as above but restricted by ranges.
- `org.apache.james.mailbox.postgres.search.DeletedSearchOverride`. Find deleted messages by looking up in the relevant Postgresql
table.
- `org.apache.james.mailbox.postgres.search.DeletedWithRangeSearchOverride`. Same as above but limited by ranges.
- `org.apache.james.mailbox.postgres.search.NotDeletedWithRangeSearchOverride`. List non deleted messages in a given range.
Lists all messages and filters out deleted message thus this is based on the following heuristic: most messages are not marked as deleted.
- `org.apache.james.mailbox.postgres.search.UnseenSearchOverride`. List unseen messages in the corresponding Postgresql index.

Please note that custom overrides can be defined here. `opensearch.search.overrides` allow specifying search overrides and is a
coma separated list of search override FQDNs. Default to none.

EG:

----
opensearch.search.overrides=org.apache.james.mailbox.postgres.search.AllSearchOverride,org.apache.james.mailbox.postgres.search.DeletedSearchOverride, org.apache.james.mailbox.postgres.search.DeletedWithRangeSearchOverride,org.apache.james.mailbox.postgres.search.NotDeletedWithRangeSearchOverride,org.apache.james.mailbox.postgres.search.UidSearchOverride,org.apache.james.mailbox.postgres.search.UnseenSearchOverride
----